spring:
  application:
    name: betting
  datasource:
    url: jdbc:mysql://autorack.proxy.rlwy.net:55523/railway
    username: root
    password: flprinltqhrWUzqCtEyCRAMRTQFJHljR
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

# stake-related properties
inhouse:
  cut:
    percentage: 0.7

allowed:
  origins:
    ${ALLOWED_ORIGINS:http://localhost:3000}