spring:
    application:
        name: betting
    profiles:
        active: ${SPRING_PROFILE_ACTIVE:dev}

    datasource:
        url: jdbc:mysql://localhost:3306/betting
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 600000

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

# stake-related properties
inhouse:
    cut:
        ratio: 0.7

bonus:
    money:
        ratio: 0.5
